// <auto-generated />
namespace OnlineTicariOtomasyonProjesiMVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class cargo1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cargo1));
        
        string IMigrationMetadata.Id
        {
            get { return "202304271525186_cargo1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
